services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_eureka_rest
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - sqlserver_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -C -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sqlserver_data:
