services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver_eureka_rest
    restart: always
    user: "root"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - sqlserver_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 800M
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sqlserver_data:
